### ISSUE TITLE
IPFS Public API and Gateway Deprecation

### ISSUE THREAD

**Issue by kevingkday** [darkcodi/nft-faucet#6]
Looks like Infura just removed public API access:

https://blog.infura.io/post/ipfs-public-api-and-gateway-deprecation

Do you have recommended code adjustment?  I'm trying to add in the custom gateway and authorization but haven't been successful yet as I'm getting a "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled." error among others.

**Comment by darkcodi** [comment]
I am doing a huge UI overhaul now. Moreover, the app will have a few more features, like **extended options for upload** (including dedicated Infura gateways), saving tokens and settings to a browser's built-in IndexedDB (for further repeated minting), stub for custom collections.
Dunno when I'll finish it, but my estimate is `~1 week`.

**Comment by kevingkday** [comment]
That's great!  Really looking forward to seeing the improvements!

**Comment by kevingkday** [comment]
How is the new UI coming along?

**Comment by darkcodi** [comment]
Half of the work is done.
It's moving slower than expected coz I have less spare time than initially planned.

**Comment by darkcodi** [comment]
Sorry for such big delay, I had other priorities irl...
I've recently finished working on that new UI. Check out release `v2.0.0`, it supports Infura dedicated gateways.
